version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:240936149117:task-definition/ChatappTaskDefinition:latest"
        LoadBalancerInfo:
          ContainerName: "ChatappTaskDefinition"
          ContainerPort: 8080
        PlatformVersion: "LATEST"